/**
 * Merge into tailwind.config theme.extend.
 * A working config using these values is at ../../knowledge-base/tailwind.config.ts.
 */
export const knowledgeBaseTheme = {
  colors: {
    accent: {
      DEFAULT: '#B0132B',
      pressed: '#8C0F22',
      surface: '#FCF3F4',
      border: '#EBC3C9',
    },
    ink: '#000000',
    body: '#1A1A1A',
    subtle: '#4D4D4D',
    muted: '#666666',
    faint: '#808080',
    ghost: '#999999',
    surface: '#FFFFFF',
    canvas: '#F2F2F2',
    sunken: '#F8F8F8',
    inverse: '#1A1A1A',
    hairline: '#D9D9D9',
    divider: '#E5E5E5',
    'divider-light': '#F2F2F2',
    'line-strong': '#808080',
    'line-disabled': '#CCCCCC',
    success: { DEFAULT: '#1B6B3A', surface: '#F2F8F4', border: '#BFD9C6' },
    warning: { DEFAULT: '#8A5A00', surface: '#FBF7EE', border: '#E6D3AE' },
    danger:  { DEFAULT: '#B0132B', surface: '#FCF3F4', border: '#EBC3C9' },
    info:    { DEFAULT: '#0B3B60', surface: '#F3F7FA', border: '#C3D4E0' },
  },
  fontFamily: {
    sans: ['Arial', 'Helvetica', 'sans-serif'],
    mono: ['ui-monospace', 'Menlo', 'monospace'],
  },
  fontSize: {
    badge:    ['10px', { lineHeight: '1.5', letterSpacing: '0.06em' }],
    micro:    ['11px', { lineHeight: '1.4', letterSpacing: '0.08em' }],
    overline: ['12px', { lineHeight: '1.4', letterSpacing: '0.08em' }],
    caption:  ['13px', { lineHeight: '1.4' }],
    sm:       ['14px', { lineHeight: '1.5' }],
    base:     ['15px', { lineHeight: '1.55' }],
    prose:    ['16px', { lineHeight: '1.7' }],
    lead:     ['17px', { lineHeight: '1.6' }],
    h3:       ['19px', { lineHeight: '1.35' }],
    h2:       ['21px', { lineHeight: '1.3' }],
    h1:       ['28px', { lineHeight: '1.25', letterSpacing: '-0.01em' }],
    display:  ['42px', { lineHeight: '1.15', letterSpacing: '-0.015em' }],
    metric:   ['29px', { lineHeight: '1' }],
  },
  borderRadius: { none: '0', sm: '2px', DEFAULT: '2px' },
  boxShadow: {
    'card-hover': '0 1px 4px rgba(0,0,0,.08)',
    menu: '0 4px 12px rgba(0,0,0,.10)',
    dialog: '0 8px 24px rgba(0,0,0,.12)',
    overlay: '0 4px 12px rgba(0,0,0,.18)',
  },
  spacing: {
    rule: '4px',
    header: '60px',
    sidebar: '272px',
    rail: '70px',
    column: '720px',
  },
  maxWidth: {
    column: '720px',
    content: '1180px',
    wide: '1280px',
    account: '940px',
    form: '400px',
  },
  screens: { sm: '480px', md: '768px', lg: '1024px', xl: '1280px' },
  keyframes: {
    fade: { from: { opacity: '0' }, to: { opacity: '1' } },
    rise: { from: { opacity: '0', transform: 'translateY(6px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
    drop: { from: { opacity: '0', transform: 'translateY(-4px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
    breathe: { '0%,100%': { opacity: '0.35' }, '50%': { opacity: '0.85' } },
  },
  animation: {
    fade: 'fade 200ms ease',
    rise: 'rise 160ms ease',
    drop: 'drop 120ms ease',
    breathe: 'breathe 1.4s ease-in-out infinite',
  },
} as const;
